In [36]:
import numpy as np
import pandas as pd
import seaborn as sns
sns.set()
import matplotlib.pyplot as plt


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [37]:
data = pd.read_csv('C:\\Users\\Ufuk Altan\\Downloads\\Downloads\\Data Science\\Machine Learning A-Z\\Part 9 - Dimensionality Reduction\\Section 43 - Principal Component Analysis (PCA)\\Wine.csv')
data.head()

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    14.23        1.71  2.43          15.6        127           2.80   
1    13.20        1.78  2.14          11.2        100           2.65   
2    13.16        2.36  2.67          18.6        101           2.80   
3    14.37        1.95  2.50          16.8        113           3.85   
4    13.24        2.59  2.87          21.0        118           2.80   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280  Proline  Customer_Segment  
0   3.92     1065                 1  
1   3.40     1050                 1  
2   3.17     1185                 1  
3   3.45     1480                 1  
4   2.93      735                 1

In [38]:
X = data.drop('Customer_Segment', axis=1)
y = data.iloc[: ,13]

In [39]:
data.skew()

Alcohol                -0.051482
Malic_Acid              1.039651
Ash                    -0.176699
Ash_Alcanity            0.213047
Magnesium               1.098191
Total_Phenols           0.086639
Flavanoids              0.025344
Nonflavanoid_Phenols    0.450151
Proanthocyanins         0.517137
Color_Intensity         0.868585
Hue                     0.021091
OD280                  -0.307285
Proline                 0.767822
Customer_Segment        0.107431
dtype: float64

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state=0)

In [41]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [45]:
X_train.shape

(142, 13)

In [27]:
from sklearn.decomposition import PCA
pca = PCA(n_components=None)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.37281068, 0.18739996, 0.10801208, 0.07619859, 0.06261922,
       0.04896412, 0.0417445 , 0.02515945, 0.02340805, 0.0184892 ,
       0.01562956, 0.01269224, 0.00687236])

In [52]:
X_train

array([[ 2.12849974e+00, -1.01973208e+00,  8.26209888e-02],
       [-2.94812519e+00, -2.54806705e-01,  1.14589113e+00],
       [ 1.91979542e+00,  1.33701156e+00, -4.02244683e-01],
       [-2.13337607e+00, -9.45897150e-01,  1.40277015e+00],
       [ 2.23680281e+00, -2.26983910e+00, -8.77499126e-01],
       [-2.28747076e+00, -1.99359253e-01,  7.97227232e-01],
       [-2.97244958e+00, -2.96522642e-01,  9.31504047e-01],
       [ 2.61809796e+00, -7.76070011e-01,  8.30660247e-02],
       [-1.04705463e+00, -3.49093326e+00, -1.29203589e+00],
       [ 2.60981596e+00,  7.34569695e-02,  1.78959140e-01],
       [ 1.52296770e-01,  2.31809388e+00,  4.97096689e-01],
       [-2.61422416e+00, -2.54812754e+00,  1.05342808e+00],
       [-2.50949512e+00, -4.27708661e-01,  9.04277766e-01],
       [ 1.72319479e+00,  9.11994596e-01, -2.15447686e+00],
       [-2.75936377e+00, -3.86681070e-01, -7.50384226e-01],
       [-2.82343185e+00, -1.89597038e+00,  6.34846718e-01],
       [ 1.36403459e+00,  8.54516419e-02

In [53]:
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train,y_train)

C:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [54]:
y_pred = classifier.predict(X_test)

In [55]:
from sklearn.metrics import confusion_matrix,accuracy_score, classification_report
confusion_matrix(y_pred, y_test)

array([[15,  0,  0],
       [ 1, 20,  0],
       [ 0,  1,  8]], dtype=int64)

In [56]:
accuracy_score(y_pred,y_test)

0.9555555555555556

In [57]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           1       0.94      1.00      0.97        15
           2       0.95      0.95      0.95        21
           3       1.00      0.89      0.94         9

    accuracy                           0.96        45
   macro avg       0.96      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45

